config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :categories
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  	@title = @category.name
  	@items = @category.items
  end

  

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
	
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  def index
	
  end
end

app/controllers/items_controller.rb
class ItemsController < InheritedResources::Base

  private

    def item_params
      params.require(:item).permit(:name, :price, :description, :category_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% @items.each do |item| %>
	<h3><%= link_to item.name,item %></h3>
	<p><%= item.description %></p>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/contact/index.html.erb
<title> Pizza 3.14 </title>
<style>
body {background-color:#222626}
h2   {color:white}
h4   {color:white}
p    {color:green}

</style>
<center><h2>Contact Information</h2></center>
<center><h4>University Glen</h4></center>
   <center> <p>University Glen Town Center </p></center>
   <center> <p>45 Rincon Drive - Suite 104A </p></center>
   <center> <p>Camarillo, CA 93012 </p></center>
   <center> <br><p>805-437-2667 office </p></center>
   <center> <p>805-437-2681 fax </p></center>
   <center> <p>universityglen@csuci.edu </p></center>
   <center> <br><p>Office Hours: </p></center>
   <center> <p>Monday - Friday: 9:00 am - 5:00 pm </p></center>
<center><br><br><h4>Pizza 3.14</h4></center>
 <center> <p>University Glen Town Center </p></center>
   <center> <p>45 Rincon Drive - Suite 101B </p></center>
   <center> <p>Camarillo, CA 93012 </p></center>
<center> <p>805-437-3674</p></center>

<center><h3><%= link_to "Back", '/main/index' %></h3></center>

app/views/hours/index.html.erb
<title> Pizza 3.14 </title>
<style>
body {background-color:#222626}
h2   {color:white}
h4   {color:white}
p    {color:green}
</style>

<center><h2>Hours</h2></center>

<center> <p>Monday-Thursday: 10:30am-9:00pm </p></center>
<center> <p>Friday: 10:30am-9:00pm</p></center>
<center> <p>Saturday & Sunday: 11:30am-9:00pm</p></center>
<center> <p>*Deliveries until 10pm</p></center>

<center><h3><%= link_to "Back", '/main/index' %></h3></center>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pizzap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<title> Pizza 3.14 </title>
<style>
body {background-color:#222626}
h1   {color:white}
p    {color:green}

</style>
<center><h1>Welcome to Pizza 3.14</h1>
<img src="http://www.universityglencorp.csuci.edu/pizza314/images/pizza314-colorlogo.jpg" alt="Pizza 3.14 Logo" style="width:367px;height:331px">
 </center>
<center>
<h3>
<%= link_to "Menu", '/categories' %>
<%= link_to "Contact Us", '/contact' %>
<%= link_to "Yelp", 'http://www.yelp.com/biz/pizza-3-14-camarillo' %>
<%= link_to "Hours", '/hours' %>
</h3>
</center>